### ISSUE TITLE
Roslyn 2.0 support

### ISSUE THREAD

**Issue by atifaziz** [aspnet/RoslynCodeDomProvider#1]
Unless it's already planned, it would be great to see support for Roslyn 2.0 added so one can use C# 7 with ASP.NET.

**Comment by Jinhuafei** [comment]
Thanks for the feedback.  We will consider it in the future release. For now, please use Microsoft.Net.Compilers 2.0+ nupkg in your project and you should good to go.

**Comment by atifaziz** [comment]
@Jinhuafei Thanks for the hint about using Microsoft.Net.Compilers 2.x. Worked like a charm. ✨

**Comment by Jinhuafei** [comment]
@atifaziz 1.0.4 version was released on Nuget. You can upgrade the package and you can use C# 7 in your project without any manual step. BTW, your project needs to be targeting to .net 4.6 and above, since Roslyn compiler 2.0 requires .net 4.6.

**Comment by atifaziz** [comment]
@Jinhuafei That's great news & thanks!
