### ISSUE TITLE
Outdated DLL libraries 

### ISSUE THREAD

**Issue by GGY-CM** [aspnet/RoslynCodeDomProvider#107]
Please refer: https://developercommunity.visualstudio.com/content/problem/689089/outdated-dll-libraries-in-microsoftcodedomprovider.html

Please check the following folder 

Microsoft.CodeDom.Providers.DotNetCompilerPlatform.3.5.0-preview1\tools\Roslyn46

Many DLLs here are really really old, 2016-11-15. the problematic DLL I mentioned still 

4.6.24705.1 (digital signed on Nov 5, 2016, version 4.3.0?)

**Comment by StephenMolloy** [comment]
I responded to the Developer Community issue, but I'll copy the response here as well for visability:

Beginning with Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0, we have had to package Roslyn binaries directly in our nupkg. We had to do this to avoid conflict with Visual Studio and how it uses Roslyn compilers. For compatibility reasons, we continue to ship with older versions of the Roslyn binaries for apps that target older frameworks. Thus Microsoft.Net.Compilers versions 1.3.2 and 2.10 and 3.5 are included in our package download... but only one of these gets copied into your project's binary output. If you target 4.7.2 or 4.8, you'll get the 3.5 Roslyn binaries copied into your binary output. The other two versions are left deep in your packages directory.

If you are using a scanner (Veracode?) to look for vulnerabilities in your project and it's finding an older version of the Roslyn binaries in your bin folder, then I would suggest targeting a framework version 4.7.2 or newer. Or you could also potentially override which version of Roslyn gets copied to your bin folder at build time using the 'RoslynToolPath' setting, or specify a different non-bin location for locating Roslyn tools at runtime using one of the "Roslyn Compiler Location" runtime options.
