### ISSUE TITLE
[3.6.0] Missing entry "aspnet:RoslynCompilerLocation" in app.config causes compile to fail

### ISSUE THREAD

**Issue by WolfgangHG** [aspnet/RoslynCodeDomProvider#113]
When upgrading our exisiting projects to 3.6.0, I noticed that this line in "app.config" was removed:

`  <appSettings>
    <add key="aspnet:RoslynCompilerLocation" value="roslyn"/>
  </appSettings>`

This causes our app to fail with a "System.IO.DirectoryNotFoundException": 
"Ein Teil des Pfades "C:\Temp\RoslynTest\RoslynTest\bin\Debug\bin\roslyn\vbc.exe" konnte nicht gefunden werden."
(translated:  "Could not find a part of the path ...")
The files are placed in "bin\Debug\roslyn", but the compiler searches them in "bin\Debug\bin\roslyn".

It works if the appSettings key is re-added.

[RoslynTest.zip](https://github.com/aspnet/RoslynCodeDomProvider/files/4946483/RoslynTest.zip)

Best regards

Wolfgang

**Comment by elGuille-MVP** [comment]
The same compiling from a desktop application.
Adding this to App.config solves the issue (thanks Wolfgang :-) ).
    <appSettings>
        <add key="aspnet:RoslynCompilerLocation" value="roslyn"/>
    </appSettings>

Guillermo

**Comment by WolfgangHG** [comment]
Just want to bring back attention to this issue. Are there any plans to repair this?

**Comment by WolfgangHG** [comment]
Was this fixed by #131 ?

**Comment by StephenMolloy** [comment]
Between #130 and #131 I think this should be resolved now. Please reopen if it's still an issue.

**Comment by WolfgangHG** [comment]
I can confirm that it works now.
