### ISSUE TITLE
License inconsistencies

### ISSUE THREAD

**Issue by JackCoplandGranta** [aspnet/RoslynCodeDomProvider#121]
The license listed in the project root and in comments at the top of several files is MIT.
But, [in the nuspec](https://github.com/aspnet/RoslynCodeDomProvider/blob/master/src/Packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.nuspec), and so also for the nuget package, a "Microsoft .Net Library" license is linked to.

What license is this code licensed under?

**Comment by Sharpe49** [comment]
Every file seems to contain reference to the MIT license. So in the NuSpec file, the license should be MIT also.

**Comment by StephenMolloy** [comment]
Fixed with #129 and #138
