### ISSUE TITLE
Install bin/roslyn files to a central location

### ISSUE THREAD

**Issue by jimbobmcgee** [aspnet/RoslynCodeDomProvider#126]
Is there any way to install the files that would normally be copied to bin/roslyn to a central location and have the ASP.NET view compilation invoke the centrally-installed version, instead of trying to invoke from ~/bin/roslyn?

We are seeing a on-the-fly view compilation issue, where our AV appears to be crashing the VBCSCompiler.exe and/or csc.exe.  

We are happy to exclude these two executables from scanning (which resolves our crashing issue) but our AV's exclusion glob syntax isn't expressive enough to target these two files across multiple deployed websites that have Nugetted the Microsoft.CodeDom.whatever package.  Entirely the fault of the AV, which I certainly don't expect you to have to worry about.

However, is there a way to install this to a common, central location, such that I can exclude that location, rather than each individual website?

If not, can such be raised as a feature request?  I guess this would take the form of an MSI (or other package) with a registry check...

**Comment by CZEMacLeod** [comment]
@jimbobmcgee  If you look at the documentation on [configuration](https://github.com/aspnet/RoslynCodeDomProvider#Configurations) it pretty much tells you how to do what you want.
Adding a `System` level Environment variable `ROSLYN_COMPILER_LOCATION` pointing to the location of the roslyn compiler.
You need to manually copy the contents of bin/roslyn to that location, but it will then be used for all applications on the machine.
You can then ensure that the folder is secure, although readable by the AppPool identities and users running compile (e.g. build servers), then exclude it from your Anti-Virus.

Hope this helps.

**Comment by jimbobmcgee** [comment]
That's great to know. I was hoping my Devs might have found this out for themselves, but it is good to have the confirmation from you.

Has this been a feature for all versions, or would this only be a recent addition?

And would this support, for example, two applications in different websites, running different versions of the MS.CodeDom... package?

**Comment by CZEMacLeod** [comment]
@jimbobmcgee Not sure when it was added - looks like April 2020, so version 3.5 of the package.
As the documentation says, setting the environment variable forces all applications to use Roslyn from that location. If the installed application was using an older version of the package, the CodeDom provider won't look at the variable though.
It looks like version 2.0 onwards support the app setting in `app.config` or `web.config` depending on if it is a web application or not.
```xml
<add key="aspnet:RoslynCompilerLocation" value="[Roslyn compiler folder full path]"/>
```
Although that would have to be set in each application separately.
There are only a dozen releases though and even for legacy apps, you can almost certainly overwrite the assembly, update the config and maybe add a binding redirect to force the newer version.
All the source code and history are in the repository - so if you need more details, I'm sure you can go hunting.
