### ISSUE TITLE
How to compile code using .net framework 4.8?

### ISSUE THREAD

**Issue by nexon33** [aspnet/RoslynCodeDomProvider#142]
I have some code that needs to be compiled dynamically to .net framework 4.8. I added the package and have the following code. (I'm using **using Microsoft.CodeDom.Providers.DotNetCompilerPlatform;**)

`
private void Form1_Load(object sender, EventArgs e)
        {
            string code = File.ReadAllText(@"C:\Users\adria\Downloads\rest.dll.amsibypass");
            string[] referencedAssemblies = new string[]
              {
            "System.dll",
            "System.Windows.Forms.dll",
            "Microsoft.CSharp.dll",
            "System.Dynamic.Runtime.dll",
            "System.Core.dll",
              };
            var compilerOptions = "/langversion:7.3 /target:exe /platform:x64 /optimize+";
            ProviderOptions options = new ProviderOptions();
            CSharpCodeProvider codeProvider = new CSharpCodeProvider();

            System.CodeDom.Compiler.CompilerParameters parameters = new CompilerParameters(referencedAssemblies);
            parameters.GenerateExecutable = true;
            parameters.CompilerOptions = compilerOptions;
            parameters.OutputAssembly = "testoutput.exe";
            CompilerResults results = codeProvider.CompileAssemblyFromSource(parameters, code);
            string errors = String.Empty;
            if (results.Errors.Count > 0)
            {
                foreach (CompilerError CompErr in results.Errors)
                {
                    errors += errors +
                        "Line number " + CompErr.Line +
                        ", Error Number: " + CompErr.ErrorNumber +
                        ", '" + CompErr.ErrorText + ";" +
                        Environment.NewLine + Environment.NewLine;
                }
            }
            if (errors != String.Empty)
                MessageBox.Show(errors);
            else
                MessageBox.Show("done!");
        }`

I already ran into some trouble when I installed the package because it couldn't find csc.exe but that was easily fixed by copying the roslyn folder to Debug/bin/roslyn instead of Debug/roslyn.

**Comment by WolfgangHG** [comment]
> I already ran into some trouble when I installed the package because it couldn't find csc.exe but that was easily fixed by copying the roslyn folder to Debug/bin/roslyn instead of Debug/roslyn.

This should be fixed by the new version 3.11 (see #113), which is hopefully released soon. 

Meanwhile, you can work around it by adding this to "app.config":
`<appSettings>
 <add key="aspnet:RoslynCompilerLocation" value="roslyn"/>
 </appSettings>`
