### ISSUE TITLE
Releasing 3.11.0 and 4.1.0

### ISSUE THREAD

**Issue by MattBussing** [aspnet/RoslynCodeDomProvider#144]
@StephenMolloy , first, thanks for keeping this updated! 

Second, are there any plans to release 3.11.0 and 4.1.0 (make them no longer prerelease/preview)? What would the ETA be?
<img width="547" alt="image" src="https://user-images.githubusercontent.com/31907187/186737246-c5f4e3af-8ffd-42c9-af03-cd6dc01185eb.png">

**Comment by StephenMolloy** [comment]
I don't have an ETA at the moment. This (and the other OOB packages for ASP.Net Classic) are unfortunately not at the top of the list of my responsibilities here. But I am trying to get them all refreshed and tidied-up at the start of the year here. This repo in particular has some feedback to address before moving out of pre-release. But I'm hoping to start looking at it next week and hopefully have something pushed to nuget within a month. (**Hope**. It's all-to-common for me to get pulled away to higher-priority fires. 😞 But this is the super-rough timeline in my head.)

**Comment by brandon-hurler** [comment]
Thank you for the quick response! Totally understandable, even if the priorities shuffle it is good to know where things are at from a high level. I appreciate it.

**Comment by fredericDelaporte** [comment]
These versions have been released two days ago, thanks. This issue should be closed.
