### ISSUE TITLE
VB.NET Project Langversion:default giving 'VB 12 does not support nameof expression'

### ISSUE THREAD

**Issue by TheConservativeCoder** [aspnet/RoslynCodeDomProvider#16]
Hi,

I have an asp.net mvc application written in vb.net and I have the latest **1.0.6** `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` nuget package installed and in some of my views that use newer language features such as string interpolation and nameof I get the squiggleys like `Visual Basic 12.0 does not support error nameof expression`. The views seem to work fine when I run the web application but I have found that I can fix this by changing the following lines in my web.config.

```xml
<system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:default /nowarn:1659;1699;1701" />
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:default /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
    </compilers>
  </system.codedom>
```

to

```xml
<system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:6.0 /nowarn:1659;1699;1701" />
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:14.0 /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
    </compilers>
  </system.codedom>
```

Also I am using Visual Studio 2017.3.

**Comment by Jinhuafei** [comment]
There is problem(crashing VS) when we specify the vb.net language version in VS2015, so we decided to use default(Let Roslyn compiler decide the language version). There is probably some reason for Roslyn to use old vb version as the default one(Maybe some breaking change). 
But anyway your workaround should be good enough to enable you use the new vb.net language features in your project.

**Comment by TheConservativeCoder** [comment]
How does roslyn decide the compiler version for `default`? I did try adding 
```
  <PropertyGroup>
     <LangVersion>14</LangVersion>
  </PropertyGroup>
```

to the vbproj file but it didn't make a difference?

**Comment by Jinhuafei** [comment]
@jcouv @jaredpar How does VB.net compiler decide the default language version?

**Comment by jcouv** [comment]
@Jinhuafei The default language version is "default", which means latest major version (15.0).
