### ISSUE TITLE
Publish issue in 1.0.7 release

### ISSUE THREAD

**Issue by Jinhuafei** [aspnet/RoslynCodeDomProvider#17]
Looks like 1.0.7 didn't fix all the publish issue. So far the following publish methods are still not working.
- OctoPack                                                          - repro'd
- publish project twice without changing project code - repro'd
- VSTS App Service Publish                                 - can't repro so far
- Azure App Service GitHub deployment            - can't repro so far
- Use local IIS in project & ctrl+F5                      - can't repro

**Comment by remcolam** [comment]
I updated My web app to 1.0.7. In the project file it is mapped to a virtual folder on my local IIS. 
![image](https://user-images.githubusercontent.com/11367055/29428260-d291ca3c-838c-11e7-8452-723fbe7e038e.png)

After compiling I open the location in the browser and it gives the following error.
![image](https://user-images.githubusercontent.com/11367055/29428361-333eecfc-838d-11e7-9e13-263349716f34.png)


Good hunting!

**Comment by Jinhuafei** [comment]
@remcolam how do you publish the compiled app unto c:\_talos\core\corepsp\pspadmin folder? Or your project is under that folder?

**Comment by remcolam** [comment]
My project is under that folder, I just compile... VS maps it to the virtual directory

**Comment by Jinhuafei** [comment]
Tried the same scenario and it worked as expected.
Would you please share the build log? Set msbuild log verbosity to diagnostic. (Tools->Options->Project and solutions->Build and Run)

**Comment by remcolam** [comment]
Sigh..... I'm trying to reproduce it again (I went back to 1.0.5 and now updated again to 1.0.7, and now it's working. 

It's getting late for me, I'm letting it rest for tonight and I will retest again tomorrow on my work machine.

**Comment by Jinhuafei** [comment]
Cool. Thanks @remcolam

**Comment by markokaa** [comment]
For me in VS2015, when I updated from 1.0.5 to 1.0.6, I received 'Could not find file ... csc.exe'. Then after I uninstalled 1.0.6 and then installed 1.0.6, it compiled in VS Build [App] but NOT with VS Build -> Publish  [App] with 'Precompile during publishing' option or in TFS2015. 

With 1.0.7, it compiles with TFS2015 but NOT VS Build -> Publish  [App] with 'Precompile during publishing' option.

**Comment by Jinhuafei** [comment]
@erincerol  I tried both scenario with 1.0.7 version and both worked for me. Would you please share your build log with me?

**Comment by Jinhuafei** [comment]
@markokaa Would you please share your build log with me?

**Comment by altso** [comment]
I upgraded from 1.0.5 to 1.0.7 and started getting this error in Visual Studio 2017 15.3.0.

When I build the project, the compiler files are not copied into `bin` folder, but into a different one. In my case it's `MyWebApp\_PublishedWebsites\MyWebApp\bin\roslyn\csc.exe` instead of expected `MyWebApp\bin\roslyn\csc.exe` (I replaced the original project name with `MyWebApp`).

When I publish, all the files are in the right place.

Unfortunately, I cannot share the full build log, but can look for any specific lines.

Hope this helps.

**Comment by remcolam** [comment]
I haven't been able to reproduce it anymore

**Comment by Jinhuafei** [comment]
@altso can you create a new Web App and compare the csproj? I suspect that you have different default target or msbuild properties.

**Comment by altso** [comment]
@Jinhuafei thanks for the suggestion. I was able to make it work in 1.0.7.

In my .csproj file i had imports in the following order (works with 1.0.5, breaks with 1.0.7):
```
  ...
  <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" Condition="false" />
  ...
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  ...
```

Moving Microsoft.CSharp.targets to the top solved the issue (works with 1.0.7):
```
  ...
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" Condition="false" />
  ...
```
I believe `$(MSBuildToolsPath)` comes from `Microsoft.Net.Compilers`, as in the new project I see `$(MSBuildBinPath)`.

**Comment by cwilli34** [comment]
I confirm this too with a Github deployment option to Azure.  I get a copy error and that /bin/roslyn is "Access Denied".  I don't have any VM directories mapped.  Nothing out of the ordinary.  1.0.7 and 1.0.6 do not build on Azure.  I had to downgrade to 1.0.5 in order to use this package.

**Comment by fonbrauzen** [comment]
> @fonbrauzen would you please provide more details on this thread?
VS 2017 (with latest public update), after upgrade from 1.0.6 to 1.0.7 1st build was as usual (with Roslyn folder and files) but next one was without them. Currently, I reverted it to 1.0.5

**Comment by Jinhuafei** [comment]
@cwilli34 Did the "copy error" happen when deploying onto Azure? If so, you may want to check if VBCSCompiler.exe is running on Azure VM.

**Comment by Jinhuafei** [comment]
@fonbrauzen Assuming the "next one" means you build the project in VS again. Did you clean up the bin folder?

**Comment by fonbrauzen** [comment]
@Jinhuafei  yes, I tried to rebuild my project few times, but no luck.

**Comment by Jinhuafei** [comment]
@fonbrauzen Just tried on my machine, it works. Can you create a new web app and upgrade DotNetCompilerPlatform to 1.0.7 version, and then compare the csproj files? Or if you can share the build log, I'll take a look.

**Comment by fonbrauzen** [comment]
@Jinhuafei  well, I tried to compare csproj files (on 2 new projects with and without it), And visually nothing changed, despite versions. In build log 
 - all as usual, except the Roslyn folder creation (as I saw yesterday). Today I tried to create few new projects and recreate this bug, but no luck. Maybe this was a side effect of some other packages. Today I received an update for VS 15.3 but tested these things without it.

**Comment by Jinhuafei** [comment]
Thanks @fonbrauzen. Let me know if you get any clue about how to repro the issue.

**Comment by cwilli34** [comment]
@Jinhuafei Yes, when using github to deploy to Azure this happens.  It doesn't happen with 1.0.5.  I am not actually using a VM, just Azure's webapp service.  I will look into how to stop the VBCSCompiler.exe from running and see if I have any luck.

**Comment by Jinhuafei** [comment]
@cwilli34 Do you have any build log that I can take a look? If you have a repro on GitHub, I can give it a try.

**Comment by 0xffffabcd** [comment]
Microsoft.CodeDom.Providers.DotNetCompilerPlatform v1.0.7 still breaks the build process. Here's the build command we're using:

`\Microsoft` Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" /m /nodeReuse:false /t:Rebuild /p:VisualStudioVersion=15.0 /p:Configuration=Release /p:TargetFrameworkVersion=v4.7  /p:AllowedReferenceRelatedFileExtensions=none /clp:PerformanceSummary;ErrorsOnly`

**Comment by Jinhuafei** [comment]
@0xffffabcd just tried the commandline with a new web app project, and Roslyn bits are copied onto bin\Roslyn folder. Is it possible to provide a build log?

**Comment by drw112** [comment]
Seeing a similar issue on our build server where it looks like on the first run the copy of the Roslyn compilter to the bin folder doesn't block and takes too long and causes the mvcbuildviews to fail.

After the build fails the first time the roslyn compilers don't get cleaned up and remain there so on subsequent runs the build succeeds on that agent.

```
[ChangeControl\ChangeControl\ChangeControl.csproj] CopyRoslynCompilerFilesToOutputDirectory
[10:40:01][CopyRoslynCompilerFilesToOutputDirectory] Copy
[10:40:01][Copy] Copying file from "[snip]\packages\Microsoft.Net.Compilers.2.3.1\build\..\tools\csc.exe" to "[snip]\[project]\[project]\bin\roslyn\csc.exe".

[MvcBuildViews] AspNetCompiler (4s)
[10:40:04][AspNetCompiler] C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_compiler.exe -v temp -p [snip]\[project]\[project]
[10:40:09][AspNetCompiler] ASPNETCOMPILER error ASPRUNTIME: Could not find file '[snip]\[project]\[project]\bin\roslyn\csc.exe'.
```

**Comment by Jinhuafei** [comment]
Thanks @drw112. Does the issue always repro on your CI machine? Is it possible to share the failed build log from your TeamCity server(before and after CopyRoslynCompilerFilesToOutputDirectory task)?

**Comment by drw112** [comment]
@Jinhuafei I'd rather not share our entire build log as I don't want to accidentally leak something secure.

It only happens the first time it builds on a particular agent.   After the first fail on an agent subsequent runs succeed.

I created a new test project using the MVC template from VS 2017 15.3.2.  I updated the Nuget packages. Restarted VS (due to the Nuget package .net compilers not uninstalling). Re-opened the project. Build. Debug and got the dreaded cannot find csc.exe

![missingcsc](https://user-images.githubusercontent.com/9697868/29629239-b8cf26b0-87fd-11e7-96c5-cace9e32943d.JPG)

I then added to the csproj
```
<MvcBuildViews>true</MvcBuildViews>
```

and lo and behold **no** problems with the build on the build server! Head scratcher

I started looking at the log file again from the first project and it contains

```
[10:40:04] :	 [ProjectName\ProjectName\ProjectName.csproj] PipelineDeployPhase
[10:40:04] :	 [PipelineDeployPhase] GetPublishingLocalizedString
[10:40:04] :	 [GetPublishingLocalizedString] Publish Pipeline Deploy Phase
[10:40:04] :	 [ProjectName\ProjectName\ProjectName.csproj] IncrementalClean
[10:40:04] :		 [IncrementalClean] Delete
[10:40:04] :	**[Delete] Deleting file "D:\BuildAgent3\work\ProjectName_Master\ProjectName\ProjectName\bin\roslyn\csc.exe".**
[10:40:04] :	[Delete] Deleting file "D:\BuildAgent3\work\ProjectName_Master\ProjectName\ProjectName\bin\roslyn\csc.exe.config".
...
```

This may be related to the MSBuild.Microsoft.VisualStudio.Web.targets?  I didn't install that on the new project and the build went through fine.  I'm honestly don't even remember what the package does.

So this may be 2 different issues.  
1) seems to be that after updating to the 1.0.7 nuget package upon first build the csc.exe file cannot be found when debugging in Visual Studio but works after a clean & build.

2) Seems to be that something (Possibly MSBuild.Microsoft.VisualStudio.Web.targets) is causing this incrementalclean to run which is deleting the csc.exe file?

**Comment by cwilli34** [comment]
@Jinhuafei I can't seem to be able to find a way to get my build logs from Azure.  I could try again, but right now I don't have time to upgrade back to 1.0.7 to try to test this since this is a production project.  It is also a private repo. I will look at this more when I have time.  Sorry I am not more help at the moment.

**Comment by Jinhuafei** [comment]
@cwilli34 No problem. Thanks for helping me investigate the issue.

**Comment by Jinhuafei** [comment]
@drw112 
For issue #1, probably because VS doesn't trigger the build, since you didn't touch any file in the project. In web app project, the Roslyn bits are copied to the bin folder during the msbuild.
For issue #2, IncrementalClean task is for removing the file produced by the prior build. It's always in the build pipeline. But it's weird to see Roslyn bits are on the clean up list which is not supposed to. Can you share the msbuild commandline you use on the CI machine? Do you have any custom task included in your project system, including the change made by some nupkg?

**Comment by fwd079** [comment]
Yeah had to revert to 1.0.5, did clean uninstall and then removed all files from packages folder, then reinstalled everything and 1.0.7 but still same issue. Anyway tracking this issue now, hopefully there'll be a fix soon.

Regards

**Comment by Jinhuafei** [comment]
@fwd079 If you can share the msbuild log, I can take a look.

**Comment by fwd079** [comment]
@Jinhuafei  I'd love to, but I have already reverted back to 1.0.5 because I am in the middle of a release cycle. Hoping to release next version of my WebAPI 2 project next week. I'll not risk it now, but can provide it after the release, if it isn't fixed by then.

Regards.

**Comment by frankfuu** [comment]
Also having the same issue with Ocotpack and 1.0.7

**Comment by 0xffffabcd** [comment]
Looking at the detailed build log it seems that it is copying the files:

```
5>Target "CopyRoslynCompilerFilesToOutputDirectory" in file "C:\Multi-Runner\builds\acf9420c\0\████\████\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.7\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props" from project "C:\Multi-Runner\builds\acf9420c\0\████\████\████\████.csproj" (target "PrepareForRun" depends on it):
       Task "Copy"
         Creating directory "C:\Multi-Runner\builds\acf9420c\0\████\████\████\bin\roslyn".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\csc.exe" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\csc.exe".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\csc.exe.config" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\csc.exe.config".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\csc.rsp" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\csc.rsp".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\csi.exe" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\csi.exe".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\csi.exe.config" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\csi.exe.config".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\csi.rsp" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\csi.rsp".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.CodeAnalysis.CSharp.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.CodeAnalysis.CSharp.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.CodeAnalysis.CSharp.Scripting.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.CodeAnalysis.CSharp.Scripting.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.CodeAnalysis.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.CodeAnalysis.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.CodeAnalysis.Scripting.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.CodeAnalysis.Scripting.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.CodeAnalysis.VisualBasic.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.CodeAnalysis.VisualBasic.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.CSharp.Core.targets" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.CSharp.Core.targets".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.DiaSymReader.Native.amd64.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.DiaSymReader.Native.amd64.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.DiaSymReader.Native.x86.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.DiaSymReader.Native.x86.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.VisualBasic.Core.targets" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.VisualBasic.Core.targets".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\Microsoft.Win32.Primitives.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\Microsoft.Win32.Primitives.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.AppContext.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.AppContext.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Collections.Immutable.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Collections.Immutable.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Console.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Console.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Diagnostics.FileVersionInfo.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Diagnostics.FileVersionInfo.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Diagnostics.Process.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Diagnostics.Process.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Diagnostics.StackTrace.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Diagnostics.StackTrace.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.IO.Compression.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.IO.Compression.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.IO.FileSystem.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.IO.FileSystem.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.IO.FileSystem.DriveInfo.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.IO.FileSystem.DriveInfo.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.IO.FileSystem.Primitives.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.IO.FileSystem.Primitives.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.IO.Pipes.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.IO.Pipes.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Reflection.Metadata.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Reflection.Metadata.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Security.AccessControl.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Security.AccessControl.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Security.Claims.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Security.Claims.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Security.Cryptography.Algorithms.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Security.Cryptography.Algorithms.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Security.Cryptography.Encoding.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Security.Cryptography.Encoding.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Security.Cryptography.Primitives.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Security.Cryptography.Primitives.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Security.Cryptography.X509Certificates.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Security.Cryptography.X509Certificates.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Security.Principal.Windows.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Security.Principal.Windows.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Text.Encoding.CodePages.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Text.Encoding.CodePages.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Threading.Thread.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Threading.Thread.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.ValueTuple.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.ValueTuple.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Xml.ReaderWriter.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Xml.ReaderWriter.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Xml.XmlDocument.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Xml.XmlDocument.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Xml.XPath.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Xml.XPath.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\System.Xml.XPath.XDocument.dll" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\System.Xml.XPath.XDocument.dll".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\vbc.exe" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\vbc.exe".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\vbc.exe.config" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\vbc.exe.config".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\vbc.rsp" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\vbc.rsp".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\VBCSCompiler.exe" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\VBCSCompiler.exe".
         Copying file from "C:\Multi-Runner\builds\acf9420c\0\████\███\packages\Microsoft.Net.Compilers.2.3.2\build\..\tools\VBCSCompiler.exe.config" to "C:\Multi-Runner\builds\acf9420c\0\████\████\███\bin\roslyn\VBCSCompiler.exe.config".
       Done executing task "Copy".
```

But the `CreateOctoPackPackage` Octopack task (using version 3.6.1.0) doesn't seem to be putting the roslyn folder inside the nuget package. 

@Jinhuafei I can send you the detailed msbuild log file but I can't post it on a public website.

**Comment by Jinhuafei** [comment]
@0xffffabcd thanks. I can repro the Octopack issue on my box. Working on the fix.

**Comment by bsimser** [comment]
Have same issue (OctoPack 3.6.1.0) on TeamCity 10x. Had to manually upload roslyn folder via FTP to site. Will test once a fix is in.

**Comment by IronSean** [comment]
I'm experiencing issues just publishing my application to Azure through the Visual Studio publish. I reverted to 1.0.5 for now.

**Comment by Jinhuafei** [comment]
@IronSean is it possible to share your msbuild log? I was able to publish my web app to Azure.

**Comment by Jinhuafei** [comment]
I made the change to fix two publish issues. (you can find the change set in [dev_1.0.8_releas](https://github.com/aspnet/RoslynCodeDomProvider/tree/dev_1.0.8_release)e branch). Can you try this private build? It's not signed yet, so you may just verify the publish scenario. Otherwise you need to do  sn.exe -Vr Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll

https://www.myget.org/feed/roslyncodedomprovider/package/nuget/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/1.0.8

**Comment by 0xffffabcd** [comment]
@Jinhuafei This package works on our build system. The "CreateOctoPackPackage" adds the roslyn folder to the package as it did with 1.0.5.

**Comment by Jinhuafei** [comment]
@0xffffabcd thanks!

**Comment by djaycee** [comment]
Hi,

I was also completely unable to publish my web projects (ASP.Net MVC5 targetting .Net4.7) with version v1.0.7, the roslyn folder was never copied under my "<project_folder_path>\obj\Production\AspnetCompileMerge\Source\bin\" folder. This version 1.0.8 fixes the problem, I can now publish. Thank you !

When do you plan on releasing a signed version on the officiel nuget repository ? I cannot perform a deployment of an unsigned library in production and we need to deploy in production asap, so we would be *very* happy to see a public release of version 1.0.8 :)

Thank you again,

JC

**Comment by bsimser** [comment]
Confirmed the changes to the .props file fixed this for me. Manually just changed that file for now but looking for the 1.0.8 release (even as a pre-release version) to update our projects. Thanks!

**Comment by saasen** [comment]
We are having this problem as well. We are using OctoPack. Is there any ETA for the update to be on nuget.org? We really don't need another feed added to our NuGet Package Manager.

**Comment by hawkunsh** [comment]
Same here. I reverted to 1.0.5 for now and waiting for a signed 1.0.8 release.

**Comment by Jinhuafei** [comment]
1.0.8 nupkg is released. I'm closing this issue. If you see any other issue, please feel free to open a new issue.

**Comment by bweber** [comment]
I upgraded a project to 1.0.8 and am seeing the same issues I saw with 1.0.7 and 1.0.6 where the roslyn folder does not copy. I reinstalled the package and it still didn't work. Downgrading to 1.0.5 worked perfectly.

**Comment by Jinhuafei** [comment]
@bweber is it possible that you share the detailed msbuild log?

**Comment by MV10** [comment]
For the record, I was fighting the missing-roslyn issue and 1.0.8 corrected the problem. In my case Publish -> Preview would break it every time, and I'd have to Publish (without Preview) on another profile to fix it.

(Maddeningly, this was reported as "Applying transformations to web.config failed," so there is another Publish bug in there somewhere relating to how publish or preview failures are reported. Wasted hours and hours chasing the wrong error message...)
