### ISSUE TITLE
cs code build in MSYS2 64 bits  and VS Code in Windows 10 creators  update .

### ISSUE THREAD

**Issue by gavinnf** [aspnet/RoslynCodeDomProvider#18]
I am using dotnet environment to build and run a working C# program and this issue happens on an off and frustrated as I have time constraints .  

Another  issue is If I open the code  cs file from VScode  
 directly , I can see the squiggly red line  but if I use code . to open at MySys prompt  file loads but squiggly lines disappear  ( in VS code erros and warning) 

Screen shot attached .
![build_fail](https://user-images.githubusercontent.com/31147184/29993175-79dbe7ca-8ff2-11e7-9d81-9824e27d255c.PNG)

Please see what can be done !

Gavinn

**Comment by Jinhuafei** [comment]
This is not related to DotNetCompilerPlatform. 
To investigate the issue, you may want to use procexp.exe to find out which process locks that assembly.
