### ISSUE TITLE
'Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' Strong name signature could not be verified

### ISSUE THREAD

**Issue by DonaldChapin** [aspnet/RoslynCodeDomProvider#20]
Functional impact

The using application cannot load because of this.  See attached Server Error details.

Minimal repro steps

   1. Create a web application project in VS 2015 Professional v15.4.1 targeting .Net framework 4.6.2
   2. Build the project in VS
   3. Run Debug or Publish to Azure Cloud Service

Expected result

The application loads properly, as it does if I revert to Microsoft.CodeDom.Providers.DotNetCompilerPlatform v1.0.5

Actual result

The following warning message is produced on Publish to Azure: 
"5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(3015,5): warning : CloudServices49 : The assembly 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll' is delay-signed."

The application fails to load with the Service Error in the attached file, both in debug on my development PC and on the published Azure Cloud Service.

Further technical details

None.

['Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.8 Signature Error.pdf](https://github.com/aspnet/RoslynCodeDomProvider/files/1404140/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8.Signature.Error.pdf)

**Comment by Jinhuafei** [comment]
@DonaldChapin did you download the package from nuget.org?

**Comment by DonaldChapin** [comment]
Yes, for the first attempt I used the VS 2017 Nuget Package Manager Console to install v1.0.8 after removing v1.0.5 and using the command given on Nuget.

 

When that didn’t work, I removed v1.0.8 and reinstalled it using the Nuget UI on the VS2017 Project menu, which didn’t work either.

 

Both attempts gave the same error message.

 

Donald

**Comment by Jinhuafei** [comment]
Can you try to clean up the nuget local cache([instruction](https://stackoverflow.com/questions/30933277/how-to-clear-nuget-package-cache-using-command-line))?

**Comment by DonaldChapin** [comment]
Cleaning up the Nuget local cache solved the problem.  Thank you very much.
