### ISSUE TITLE
roslyn not getting copied into bin folder

### ISSUE THREAD

**Issue by willbush** [aspnet/RoslynCodeDomProvider#21]
This issues exists in versions after 1.0.5.

Reproduction steps:

1. Create a new Console App on .NET Framework 4.6.1
2. Install Microsoft.CodeDom.Providers.DotNetCompilerPlatform via NuGet
3. I was trying to compile a basic "hello world" source using interpolated strings see below:

```csharp
using System;
using System.CodeDom.Compiler;
using Microsoft.CodeDom.Providers.DotNetCompilerPlatform;

namespace CodeDomTest
{
    internal class Program
    {
        const string Source = @"
namespace Samples {
    using System;

    public class Class1 {

    public static void Main() {
      var bob = ""Bob"";
      Console.WriteLine($""Hello World! {bob}"");
      Console.WriteLine(""Press the Enter key to continue."");
      Console.ReadLine();
    }
  }
}
";
        static void Main()
        {
            var provider = new CSharpCodeProvider();
            var result = provider.CompileAssemblyFromSource(new CompilerParameters(), Source);

            if (result.Errors.HasErrors)
            {
                foreach (var error in result.Errors)
                {
                    Console.WriteLine(error);
                }
            }
            else
            {
                Console.WriteLine("done with no errors");
            }
            Console.WriteLine("Press the Enter key to continue.");
            Console.ReadLine();
        }
    }
}
```
4. look in /bin/Debug and you will not find Roslyn.

I would expect the above program to run and print "done with no errors"

**Comment by willbush** [comment]
Here is an example of the above program working in 1.0.5 with the [path to roslyn hacked through reflection](https://stackoverflow.com/questions/31639602/using-c-sharp-6-features-with-codedomprovider-rosyln), which was the bug that was fixed in 1.0.6.

```csharp
using System;
using System.CodeDom.Compiler;
using System.Reflection;
using Microsoft.CodeDom.Providers.DotNetCompilerPlatform;

namespace ConsoleApp3
{
  internal class Program
  {
    const string Source = @"
namespace Samples {
  using System;

  public class Class1 {

    public static void Main() {
      var bob = ""Bob"";
      Console.WriteLine($""Hello World! {bob}"");
      Console.WriteLine(""Press the Enter key to continue."");
      Console.ReadLine();
    }
  }
}
";

    static void Main()
    {
      var provider = GetPathHackedProvider();

      var result = provider.CompileAssemblyFromSource(new CompilerParameters(), Source);

      if (result.Errors.HasErrors)
      {
        foreach (var error in result.Errors)
        {
          Console.WriteLine(error);
        }
      }
      else
      {
        Console.WriteLine("done with no errors");
      }
      Console.WriteLine("Press the Enter key to continue.");
      Console.ReadLine();
    }

    static CSharpCodeProvider GetPathHackedProvider()
    {
      var provider = new CSharpCodeProvider();
      var settings = provider
        .GetType()
        .GetField("_compilerSettings", BindingFlags.Instance | BindingFlags.NonPublic)
        .GetValue(provider);
      var path = settings.GetType().GetField("_compilerFullPath", BindingFlags.Instance | BindingFlags.NonPublic);
      path.SetValue(settings, ((string)path.GetValue(settings)).Replace(@"bin\roslyn\", @"roslyn\"));

      return provider;
    }
  }
}
```

**Comment by willbush** [comment]
The issues is that console apps (and probably WPF apps) don't define a "WebProjectOutputDir" and once I added it to the project file 1.0.8 now copies roslyn to the bin folder.

```xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <WebProjectOutputDir>bin\Debug\</WebProjectOutputDir>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <WebProjectOutputDir>bin\Release\</WebProjectOutputDir>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
```

In the "props" file that defines how this is copied it has the following:

```xml
  <Target Name="CopyRoslynCompilerFilesToOutputDirectory" AfterTargets="CopyFilesToOutputDirectory">
    <Copy SourceFiles="@(RoslyCompilerFiles)" DestinationFolder="$(WebProjectOutputDir)\bin\roslyn" ContinueOnError="true" SkipUnchangedFiles="true" Retries="0" />
  </Target>
```
Perhaps it should not be continue on error? I'm not sure exactly how this should be fixed, but adding that variable to the csproj file fixed it for me.

**Comment by Jinhuafei** [comment]
Thanks @willbush . This provider is originally designed for asp.net web app. We will consider to add non-web app support in future. BTW, feel free to send a PR.

**Comment by willbush** [comment]
Alright, I did not realize this was intended to be used only for asp.net. However, I'm not aware of any alternatives if I want to dynamically compile C# 6 code. I'll probably just live with adding the WebProjectOutputDir to my project file for now.

**Comment by willbush** [comment]
Another thing I realized about this, and this probably applies to asp.net as well. When I install this in a library X, and I have several other libraries that pulls in my library X, then they also have to install this library through nuget so that Roslyn will get included in the bin folder. Is this even something that could be handled automatically?

Right now I have a library that does code generation and compilation dynamical, about 4 other libraries depend on this library, and in those libraries I have to add the output path to their csproj files and install this RoslynCodeDomProvider so that Roslyn ends up in their output path.

**Comment by Rzpeg** [comment]
Upgrading to 1.0.8 hasn't solved the issue. We are using the "PackageReference" Nuget format.
MVC5, Target 4.6.1, "Remove Additional Files at destination" is checked.

**Comment by Jinhuafei** [comment]
@Rzpeg can you provide repro steps? This issue is about using the CodeDom provider nupkg in non-web app. If your issue is in web project, please open a new issue.

**Comment by Jinhuafei** [comment]
2.0.0-preview is released. Microsoft.CodeDom.Providers.DotNetCompilerPlatform now supports non-web projects. After upgrading it, please remember to uninstall Microsoft.Net.Compilers nupkg in your project.

**Comment by vcarlucci** [comment]
Installing nugpkg Microsoft.CodeDom.Providers.DotNetCompilerPlatform 2.0.0 fails. We tried it on a class library (.Net Framework) project with .NET version 4.7.02558. Here the message.

PM> Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -Version 2.0.0 

Attempting to gather dependency information for package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0' with respect to project 'FormsRapidTest', targeting '.NETFramework,Version=v4.6.1'
Install-Package : Package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform 2.0.0' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are available (OR) 
package id, version are specified correctly.
At line:1 char:1
+ Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -V ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:00.9535704

**Comment by vcarlucci** [comment]
uups, version 2.0.0 is in preview, I didn't saw it. It works of course!

**Comment by smorrisfv** [comment]
Hi there,

I've installed version 2 of this within my project.  It is a non-web project and when I compile it it outputs `csc.exe` in the `bin\Debug` directory witin `bin\roslyn`, so `bin\Debug\bin\roslyn`.  However, when I run my application it crashes with the error

```
Oh nose... I died: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\source\Application1\bin\Debug\roslyn\csc.exe'
```

Since the `exe` is in the `bin\roslyn` directory it is looking in the wrong spot.  Is there a way to redirect to the right spot?  Or change the output dir of `csc.exe`?

**Comment by Jinhuafei** [comment]
@smorrisfv you can update the compiler location through the appsetting in your app.config. All the configuration details can be found on the [project home page](https://github.com/aspnet/RoslynCodeDomProvider)
```
<add key="aspnet:RoslynCompilerLocation" value="[Roslyn compiler folder full path]"/>
```

**Comment by smorrisfv** [comment]
Thanks @Jinhuafei , worked perfectly!

**Comment by smorrisfv** [comment]
I've just upgraded my product to work with .NET Standard tools and have noticed that the compiler isn't being output to to the build folder.  I'm not sure if this is a seperate bug or not, if so then I'll open a new ticket.

My target framework is `net46`.

**Comment by Jinhuafei** [comment]
Are you using packagereference in your project(nupkg ref is added into csproj file, not packages.config)? If so, then this is a different issue. Please open a new issue.

**Comment by chucklu** [comment]
Hi @Jinhuafei ,
    It did not work with **asp.net webforms site** project even if I update the codedom version to 2.0.0 .
![image](https://user-images.githubusercontent.com/3004057/43298592-3756967c-9189-11e8-8fe8-77d78979d553.png)
    
     When I build the website, the NuGet won't copy the roslyn folder to bin folder.

**Comment by eltomjan** [comment]
There was a typo @willbush's fix - missing **n** in (RoslyCompilerFiles) instead of Rosly**n**CompilerFiles, fixed looks like this:

```xml
  <Target Name="CopyRoslynCompilerFilesToOutputDirectory" AfterTargets="CopyFilesToOutputDirectory">
    <Copy SourceFiles="@(RoslyCompilerFiles)" DestinationFolder="$(WebProjectOutputDir)\bin\roslyn" ContinueOnError="true" SkipUnchangedFiles="true" Retries="0" />
  </Target>
```

Btw my SampleWebApp.csproj from https://github.com/JonPSmith/SampleMvcWebApp
had this instead (placed Roslyn next2) and works without problems now:
```
  <Target Name="MvcBuildViews" AfterTargets="AfterBuild" Condition="'$(MvcBuildViews)'=='true'">
    <AspNetCompiler VirtualPath="temp" PhysicalPath="$(WebProjectOutputDir)" />
  </Target>
```

> The issue is that console apps (and probably WPF apps) don't define a "WebProjectOutputDir" and once I added it to the project file 1.0.8 now copies roslyn to the bin folder.
> 
> ```
>   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
>     <PlatformTarget>AnyCPU</PlatformTarget>
>     <DebugSymbols>true</DebugSymbols>
>     <DebugType>full</DebugType>
>     <Optimize>false</Optimize>
>     <OutputPath>bin\Debug\</OutputPath>
>     <WebProjectOutputDir>bin\Debug\</WebProjectOutputDir>
>     <DefineConstants>DEBUG;TRACE</DefineConstants>
>     <ErrorReport>prompt</ErrorReport>
>     <WarningLevel>4</WarningLevel>
>   </PropertyGroup>
>   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
>     <PlatformTarget>AnyCPU</PlatformTarget>
>     <DebugType>pdbonly</DebugType>
>     <Optimize>true</Optimize>
>     <OutputPath>bin\Release\</OutputPath>
>     <WebProjectOutputDir>bin\Release\</WebProjectOutputDir>
>     <DefineConstants>TRACE</DefineConstants>
>     <ErrorReport>prompt</ErrorReport>
>     <WarningLevel>4</WarningLevel>
>   </PropertyGroup>
> ```
> 
> In the "props" file that defines how this is copied it has the following:
> 
> ```
>   <Target Name="CopyRoslynCompilerFilesToOutputDirectory" AfterTargets="CopyFilesToOutputDirectory">
>     <Copy SourceFiles="@(RoslyCompilerFiles)" DestinationFolder="$(WebProjectOutputDir)\bin\roslyn" ContinueOnError="true" SkipUnchangedFiles="true" Retries="0" />
>   </Target>
> ```
> 
> Perhaps it should not be continue on error? I'm not sure exactly how this should be fixed, but adding that variable to the csproj file fixed it for me.
