### ISSUE TITLE
Update NuGet package description with changeset link

### ISSUE THREAD

**Issue by BenedekFarkas** [aspnet/RoslynCodeDomProvider#24]
This is just a suggestion: Similar to the [Microsoft.Net.Compilers](https://www.nuget.org/packages/Microsoft.Net.Compilers) package, I think it would be useful if the description of the package would include a link to the changeset, from which the package was built (also to make it easier to find this repository).

**Comment by Jinhuafei** [comment]
thanks for the suggestion @BenedekFarkas . We are using GitHub Releases feature to correlate the nupkg and the source.

**Comment by BenedekFarkas** [comment]
I can see that, but what I'm talking about is a link the other way. If you just look at the NuGet package, it's not obvious that this repository hosts its source code (the name of the package and the repository is also different).

**Comment by Jinhuafei** [comment]
Makes sense. Will add a link to the releases tag on nuget.org

**Comment by Jinhuafei** [comment]
This is actually from the nuspec. Need to modify the build the process.  Will do some investigation.

**Comment by Jinhuafei** [comment]
This will be added in 1.0.9 release.
