### ISSUE TITLE
CSharpCodeProvider fails on .net core with TypeLoadException: Could not load type 'System.Security.Principal.WindowsImpersonationContext' from assembly 'mscorlib'

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/RoslynCodeDomProvider#37]
I expected that CSharpCodeProvider from this repo is a cross-platform CodeDom-provider build around Roslyn which is also cross-platform. But it turned out that CSharpCodeProvider is bound to Windows as it uses WindowImpersonationContext for some reason:

https://github.com/aspnet/RoslynCodeDomProvider/blob/707c08cf1ea8947548da316a0891213578b1779a/src/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/Compiler.cs#L189

So a try to compile any code in dotnet core project fails with System.TypeLoadException: 'Could not load type 'System.Security.Principal.WindowsImpersonationContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'

It kills all the glory idea of cross-platform CSharpCodeProvider. Is it on purpose made as Windows-only solution?
Please make it cross-platform!

**Comment by Jinhuafei** [comment]
@evil-shrike codedom provider is only for full .net framework, not for .net core. What's your use case on .net core?

**Comment by evil-shrike** [comment]
@Jinhuafei probably I started digging into the thing without enough knowledge. But I can share how I came to the idea that I need RoslynCodeDomProvider. 
I have a lib for reporting. It allows designing reports in some xml layouts with macros. One of macro types is C# code. Previously the lib was targeted net45 and now I'm trying to migrate it onto netcore. 
There's no CodeDOM in .net core, yes, but there's a compatibility package System.CodeDom which installs into netcore projects. The only problem is that CSharpProvider throws `PlatformNotSupportedException` in method `CompileAssemblyFromSource` whitch I use. So I decided to switch CSharpProvider onto RoslynCodeDomProvider as I though it's a drop-in replacement but based on Roslyn. But it turned out it's not. It's Windows-based and uses csc.exe instead of Roslyn API.

**Comment by Jinhuafei** [comment]
RoslynCodeDomProvider uses Roslyn compiler to compile the code. There are two options to compile the code with Roslyn. One is to host the Roslyn in process(I think this is what you mean by calling Roslyn API). The other one is to use Roslyn compiler process. We chose to use the second way(you can find the reason that we chose this in [this thread](https://github.com/aspnet/RoslynCodeDomProvider/issues/2)). For now, we don't have any plan to port RoslynCodeDomProvider to .net core. But thanks for letting us know your scenario. We will consider it in future release.
