### ISSUE TITLE
CSharpCodeProvider vs Roslyn, round 2

### ISSUE THREAD

**Issue by jmarolf** [aspnet/RoslynCodeDomProvider#46]
moved from https://github.com/dotnet/roslyn/issues/26729 on behalf of @codemonkey493 

**Version Used**: 
```
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.8" targetFramework="net462" />
  <package id="Microsoft.Net.Compilers" version="2.8.0" targetFramework="net462" developmentDependency="true" />
```

**Steps to Reproduce**:

1. Create a fresh package with the packages above
2. create a CSharpCodeProvider object
3. Call CompileAssemblyFromFile()

**Expected Behavior**:
Compile.

**Actual Behavior**:
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'D:\Projects\MyProject\Bin\bin\roslyn\csc.exe'.'
(bin or roslyn folders aren't present in the D:\Projects\MyProject\Bin folder at all)

**Comment by Jinhuafei** [comment]
@codemonkey493 please try [2.0.0-preview](https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/2.0.0-preview).

**Comment by beyarkay** [comment]
Future travelers, you're probably looking for the latest version of the `DotNetCompilerPlatform`: https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform
