### ISSUE TITLE
Advice is wrong

### ISSUE THREAD

**Issue by PhilPJL** [aspnet/RoslynCodeDomProvider#50]
In your advice you say:
> If you are using Visual Studio 2017 with latest update, you should upgrade Microsoft.CodeDom.Providers.DotNetCompilerPlatform nupkg to 2.0.0 and remove Microsoft.Net.Compilers nupkg from your project.

However the point of installing Microsoft.Net.Compilers is to build using the latest version on whichever machine is building the code.  For example we are stuck using TFS 2013 and a TFS 2013/5 build server.  The build server doesn't recognize the VS 2017 build tools so we need the package installed in every project.

**Comment by Jinhuafei** [comment]
Thanks for your feedback @PhilPJL .  The trade-off behind this decision is to provide much better perf when compiling the web projects in VS 2017 by default. We understand this may break some customers who are still using old version of VS, so we still keep the option for them to use Microsoft.Net.Compilers in their projects. In your case, you can upgrade DotNetCompilerPlatform to 2.0.0 and also keep Microsoft.Net.Compilers in your project. This setting should still work on your TFS 2013 build server. The drawback of it is that you won't get the perf improvement in your dev environment using latest VS2017. Oh, wait maybe you can do this in your csproj file and set BuildServerProperty in your build server.

 ```
<Import Project="..\packages\Microsoft.Net.Compilers.2.6.1\build\Microsoft.Net.Compilers.props" Condition="Exists('..\packages\Microsoft.Net.Compilers.2.6.1\build\Microsoft.Net.Compilers.props') AND $(BuildServerProperty)' != ''" />
```

**Comment by PhilPJL** [comment]
@Jinhuafei How much performance difference would you expect?  If it's a lot why doesn't VS special case this nuget package somehow so that it uses the ngen'ed version if possible.

**Comment by PhilPJL** [comment]
@Jinhuafei Looks like I've answered my own question.  If I ngen csc.exe and VBCSCompiler.exe in the .net compiler package folder the build time for our solution of 180 projects goes from

Machine 1 (8700K - my home machine): 150 seconds to 60 seconds, which is fantastic!
Machine 2 (crappy VM - my work machine - yes really) : 1080 seconds to 900 - not so good

Thanks for the hint.  It's turned out to be very useful.

**Comment by Jinhuafei** [comment]
Yes, NGen can improve the cold startup perf by reducing the JIT cost.
