### ISSUE TITLE
V1.0.8/V2.0.0 Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props error

### ISSUE THREAD

**Issue by PhilPJL** [aspnet/RoslynCodeDomProvider#52]
As mentioned in another issue I raised, I have a solution were most projects use the .Microsoft.NET.Compilers package so that our build server works correctly.
I've discovered it's possible when building on a local machine, to use the VS compiler (which turns out to be 5x faster than the compiler package) by setting the environment variable 'UseSharedCompilation'='true'.

If I set the variable I get multiple build failures because of errors in the .props files associated with V1.0.8 and V2.0.0.

Using VS 2017 15.7.3

In 1.0.8:

These variables should say 'RoslynCompilerFiles'

![image](https://user-images.githubusercontent.com/271656/41500590-876ade9c-718c-11e8-953d-923c614f3ae5.png)

Otherwise we get these rather worrying warnings

![image](https://user-images.githubusercontent.com/271656/41500638-7fe2e056-718d-11e8-9d87-110c5588ff94.png)

and

![image](https://user-images.githubusercontent.com/271656/41500639-8f3ab9c0-718d-11e8-8793-08e46a231dfc.png)

Correcting the misspelled variable fixes both issues.

In 2.0.0:

The null ref exception is still intermittently present.

This is throwing a null-ref

![image](https://user-images.githubusercontent.com/271656/41500652-cc64d27c-718d-11e8-82a4-78ab5fc8b14f.png)

I suggest you change it to this which fixes the issue

![image](https://user-images.githubusercontent.com/271656/41500785-118d49ae-7190-11e8-9f13-9c64573594e5.png)
       

The fix is required in 1.0.8 and 2.0.0.

Although these fixes mean that the build works when 'UseSharedCompilation'='true', we need V2.0.0 installed or the web site won't run because there's then no copy of the Roslyn tools folder if V1.0.8 is installed.

**Comment by Jinhuafei** [comment]
I wasn't able to repro the issue with setting UseSharedCompilation. Can you share the repro steps or msbuild diag log?

**Comment by PhilPJL** [comment]
Repro for first bug is easy.

Ensure the environment variable UseSharedCompilation=true.
Restart VS 2017 if you have it open.
Create a new MVC app in VS 2017 which contains both Microsoft.Net.Compilers (2.6.1) and Microsoft.CodeDom.Providers.DotNetCompilerPlatform (1.0.8)
Build. There are 6 warnings such as  'could not copy the file "swapfil.sys" because it was not found'
This is easily fixed by changing 'RoslyCompilerFiles' to 'RoslynCompilerFiles'.

The second issue doesn't seem to occur in a single project solution.  It happens intermittently in a solution with several web projects, 20 in our case.

Upgrade to DotNetCompilerPlatform 2.0.  'RoslyCompilerFiles' has already been fixed.


                            var mo = results.Cast<ManagementObject>().FirstOrDefault();
                            Log.LogMessage("ExecutablePath is {0}", (string)mo["ExecutablePath"]);
                            if(mo != null && ((string)mo["ExecutablePath"]).StartsWith(ImagePath, StringComparison.OrdinalIgnoreCase))

**Comment by Jinhuafei** [comment]
Didn't get the luck to repro the second issue, but I'll fix the code you pointed out.

**Comment by StasPerekrestov** [comment]
Hi. My team experiences the same issue

![image](https://user-images.githubusercontent.com/838093/42879685-25e94cc2-8a9a-11e8-8038-cdb7bf17059c.png)

**Comment by Jinhuafei** [comment]
@dreschner The fix is included in 2.0.1 release.

**Comment by voiplab** [comment]
@Jinhuafei this fix doesn't work fine. We still have got the same error time after time while build solution

`Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(36, 5): Object reference not set to an instance of an object.`

**Comment by Jinhuafei** [comment]
@voiplab Do you have repro steps for the issue?
