### ISSUE TITLE
Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(31,5): error : MSB4801 error MSB4175

### ISSUE THREAD

**Issue by WeihanLi** [aspnet/RoslynCodeDomProvider#56]
When I build my project(target with net452) with `dotnet build`, I meet the error as follows:

> C:\Users\liweihan.TUHU\.nuget\packages\microsoft.codedom.providers.dotnetcompilerplatform\2.0.0\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(31,5): error : MSB4801: 任务工厂“CodeTaskFactory”在 MSBuild 的 .NET Core 版本上不受支持。 [D:\Document\projects\ProjectsSource\DbTool\src\DbTool\DbTool.csproj]
C:\Users\liweihan.TUHU\.nuget\packages\microsoft.codedom.providers.dotnetcompilerplatform\2.0.0\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(31,5): error MSB4175: 未能从程序集“C:\Program Files\dotnet\sdk\2.1.301\Microsoft.Build.Tasks.Core.dll”加载任务工厂“CodeTaskFactory”。任务工厂必须对 "TaskType" 属性返回一个值。 [D:\Document\projects\ProjectsSource\DbTool\src\DbTool\DbTool.csproj]

my project is [here](https://github.com/WeihanLi/DbTool/tree/wfdev) if you need

**Comment by WeihanLi** [comment]
build it with `Visual Studio` is normal

**Comment by Jinhuafei** [comment]
Thanks @WeihanLi . This is the same issue as [this one](https://github.com/aspnet/RoslynCodeDomProvider/issues/51)
