### ISSUE TITLE
Unable to copy roslyn files due to file lock from VBCSCompiler.exe

### ISSUE THREAD

**Issue by dreschner** [aspnet/RoslynCodeDomProvider#57]
Even we are on version 2.0.0, we experience some issues with locks from the VBCSCompiler.exe (see logs).

```18>Unable to add 'bin/roslyn/Microsoft.CodeAnalysis.CSharp.dll' to the Web site.  Unable to add file 'bin/roslyn/Microsoft.CodeAnalysis.CSharp.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/Microsoft.CodeAnalysis.dll' to the Web site.  Unable to add file 'bin/roslyn/Microsoft.CodeAnalysis.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/Microsoft.CodeAnalysis.VisualBasic.dll' to the Web site.  Unable to add file 'bin/roslyn/Microsoft.CodeAnalysis.VisualBasic.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/Microsoft.DiaSymReader.Native.amd64.dll' to the Web site.  Unable to add file 'bin/roslyn/Microsoft.DiaSymReader.Native.amd64.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/System.Collections.Immutable.dll' to the Web site.  Unable to add file 'bin/roslyn/System.Collections.Immutable.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/System.IO.Compression.dll' to the Web site.  Unable to add file 'bin/roslyn/System.IO.Compression.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/System.IO.FileSystem.dll' to the Web site.  Unable to add file 'bin/roslyn/System.IO.FileSystem.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/System.IO.FileSystem.Primitives.dll' to the Web site.  Unable to add file 'bin/roslyn/System.IO.FileSystem.Primitives.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/System.Reflection.Metadata.dll' to the Web site.  Unable to add file 'bin/roslyn/System.Reflection.Metadata.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/System.Security.Cryptography.Primitives.dll' to the Web site.  Unable to add file 'bin/roslyn/System.Security.Cryptography.Primitives.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/System.ValueTuple.dll' to the Web site.  Unable to add file 'bin/roslyn/System.ValueTuple.dll'.  The process cannot access the file because it is being used by another process.
18>Unable to add 'bin/roslyn/VBCSCompiler.exe' to the Web site.  Unable to add file 'bin/roslyn/VBCSCompiler.exe'.  The process cannot access the file because it is being used by another process.
```

We're unsure what we could do to assist you to analyse the issue..?

**Comment by Jinhuafei** [comment]
Is this a web site project?

**Comment by dreschner** [comment]
Yes, it happens on a web site project.

**Comment by dreschner** [comment]
Happend again, but this time, even visual studio crashed. But I'm not sure if it does mean anything, as vs sometimes crashes at the end of the publishing.

![image](https://user-images.githubusercontent.com/34408442/43249107-1b4bfd98-90ba-11e8-804b-52695fe78917.png)

**Comment by dreschner** [comment]
And here are the lock handles from process explorer as the problem occurs
![image](https://user-images.githubusercontent.com/34408442/43249449-fb045e4e-90ba-11e8-88d6-57a67c977a25.png)

**Comment by Jinhuafei** [comment]
VBCSCompiler.exe is the Roslyn compiler service process which is used to do asp.net runtime compilation. You can kill this process before publishing, or use [CheckIfShouldKillVBCSCompiler](https://github.com/aspnet/RoslynCodeDomProvider/blob/master/src/Packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/build/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props) in [sitename].publishproj.

**Comment by dreschner** [comment]
Ahh, so, it is necessary to include CheckIfShouldKillVBCSCompiler in the MSBuild pipeline? I thought that it would be done automatically by RoslynCodeDomProvider at buildtime or before/while publishing! Will try that then.

**Comment by dreschner** [comment]
Hmm, but I'm a little bit unsure if it shouldn't work anyway. We have the publish settings in our csproj file, and in there, we have 

`<Import Project="..\..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props" Condition="Exists('..\..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')" />`

right at the top of the file as it was included by the NuGet installation anyway. Aditionally, we have

```  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props'))" />
  </Target>```

at the end, so, it should get an error when it doesn't see the props file. All web projects are MVC.NET with framework 4.6.1. The projects are under `C:\Dev\Project`, while the web deploy targets to `C:\inetpub\wwwroot\dev-standalone\Website`.

So, am I wrong? Is there any possibility to check if he tries to kill the VBCSCompiler.exe processes?

**Comment by dreschner** [comment]
Ahh, I see what you mean!

In CheckIfShouldKillVBCSCompiler, you check if the VBCSCompiler in $(RoslynToolsDestinationFolder) will be overwriten. As $(RoslynToolsDestinationFolder) is C:\Dev\Project\Source\Web\bin\roslyn\ it will check against our build folder, where File.Exists(Src) && File.Exists(Dest) && (File.GetLastWriteTime(Src) != File.GetLastWriteTime(Dest)) will only be true if we update the RoslynCodeDomProvider. So, only when we would update the NuGet package, the VBCSCompiler.exe would be killed.

But because we use web deploy, it should always be killed in our development environment. I did that now with the following lines in our *.csproj (we don't have a *.publishproj in our solution; should we have one in our web projects with ASP.NET MVC 5?):

```
<Target Name="CheckIfShouldKillVBCSCompiler">
  <PropertyGroup>
    <ShouldKillVBCSCompiler>true</ShouldKillVBCSCompiler>
  </PropertyGroup>
</Target>
```

which works fine for us.

Thank you very much for your support; you can close the ticket now. I'll leave it open, as I'm not sure if you're able to answer my question reguarding the *.publishproj file if I'll do it.

**Comment by Jinhuafei** [comment]
If there is csproj file under your web app folder, then this is a web application project(not web site project). For web application project, you don't need *.publishproj file, because the publishing task can be put into the csproj. 
I wasn't able to repro the issue. Can you provide publish msbuild log? Maybe I can make some change to fix the problem.

**Comment by dreschner** [comment]
Ahh, yeah, sorry for the confussion by my little mistake!

I've reproduced it once more and add you a build log from visual studio. As I don't want to show the customers name, I've replaced all "dangerous" informations with Amstrad. Hope that it's still readable.

[buildlog-vbcscompiler-problem.txt](https://github.com/aspnet/RoslynCodeDomProvider/files/2236870/buildlog-vbcscompiler-problem.txt)

**Comment by Jinhuafei** [comment]
Thanks for the log file. I'll take a look and see what I can do.

**Comment by dreschner** [comment]
Had the described error message right now. Here is a screenshot of the error and the msbuild log. Hope that you have a better solution in the long term.

![object-error](https://user-images.githubusercontent.com/34408442/43408642-295a2412-9422-11e8-8842-57410c32731b.png)
[msbuild-object-error.zip](https://github.com/aspnet/RoslynCodeDomProvider/files/2241922/msbuild-object-error.zip)

**Comment by dreschner** [comment]
I have problems at the moment even with my workaround. I'm a little bit confused what does fail here...?

Here is the log: 
[msbuild-with-workaround.txt](https://github.com/aspnet/RoslynCodeDomProvider/files/2257364/msbuild-with-workaround.txt)

**Comment by Jinhuafei** [comment]
As I mentioned in issue #58, the VBCSCompiler.exe process is started by asp.net to do the runtime compilation on the web server which fails the publish because of the file lock. The workaround is only for the lock issue at build time on your dev box or CI box. If fully pre-compiling the views is not an option for you, you may consider to specify the TTL of Roslyn compiler server(you can find more info [here](https://github.com/aspnet/RoslynCodeDomProvider)) to have VBCSCompiler process auto shutdown sooner.

**Comment by edika99** [comment]
same here only for bin/roslyn/Microsoft.CodeAnalysis.VisualBasic.dll on Visual Studio 2017 on webform project in c#
