### ISSUE TITLE
Pre compile ASP.NET web application with roslyn

### ISSUE THREAD

**Issue by ranuka2** [aspnet/RoslynCodeDomProvider#6]
I'm developing a Visual Studio 2015 extension which need to to pre compile a selected .aspx file and emit the output to a target location. The compiled binary will be submitted to a service for analysis. Is it possible to Roslyn compiler platform to pre-compile a single .aspx file? If so, Please let me know the high level steps.

**Comment by Jinhuafei** [comment]
Asp.net generates code for aspx page and groups them by folder and eventually pass the generated code file to RoslynCodeDomProvider which compiles them to assemblies.
