### ISSUE TITLE
Missing F# Provider 

### ISSUE THREAD

**Issue by ststeiger** [aspnet/RoslynCodeDomProvider#64]
It's missing a F# Provider. 
There's a VBCompiler and a CSharpCompiler. 
```
CSharpCompiler.cs
VBCompiler.cs
```

Where is the F# Compiler ?

**Comment by Jinhuafei** [comment]
@ststeiger Thanks for your feedback. Currently we don't have plan to add F# provider.

**Comment by ststeiger** [comment]
@Jinhuafei: Thanks for the answer. 
I'll re-translate this to: 
There is none - not now and not in the future either.
