### ISSUE TITLE
Roslyn folder not copied to the \bin in Visual Studio

### ISSUE THREAD

**Issue by KubaOczko** [aspnet/RoslynCodeDomProvider#66]
If you open a web project in Visual Studio (tried with VS 2017 15.8.9)  without restored nuget packages the roslyn folder isn't copied after build. It seems that RoslynToolPath property defined in Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Extensions.props is not re-evaluated on each build.

STR:
- Open following "empty" solution with one web project.
 [Solution1.zip](https://github.com/aspnet/RoslynCodeDomProvider/files/2548173/Solution1.zip)
- Restore nuget packages
- Rebuild solution
- Roslyn folder is not available in bin folder

Workaround:
- Reopen Visual Studio or reload web project and try it again...

**Comment by MasihAkbari** [comment]
why this issue is not fixed already? it's been on and off on each release and now it's not working again in release 2.0.1

simple workaround is this command after build and restore nuggets:
`Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r`

**Comment by StephenMolloy** [comment]
Should be fixed with #87.

**Comment by niemyjski** [comment]
Can we get a new release so we can try out these changes...

**Comment by niemyjski** [comment]
I hope this will resolve our issue where our VS Package wasn't including the roslyn folder in the VSIX.
