### ISSUE TITLE
Obsolete Warnings 612, 618 are disabled in csharp

### ISSUE THREAD

**Issue by FSDKO** [aspnet/RoslynCodeDomProvider#86]
The method `CSharpCompiler.FixUpCompilerParameters(CompilerParameters)` adds the Argument `/nowarn:1659;1699;1701;612;618` to the compile parameters. So the both Obsolete warnings 612 and 618 are suppressed.
I have no chance to enable these warnings.

Btw - so the content of the CompileParameters instance, given to `CSharpCodeProvider.CompileAssemblyFromFile(..)`, is modified - EACH time I give this instance to the method. This is very "dirty".

**Comment by StephenMolloy** [comment]
In an ASP.Net scenario, we magically add these warnings to be ignored. If you're calling into the codedom providers directly, then this is probably turned off by default and the compiler options you see in config are what you get. Either way, you can turn off the ASP.Net-style argument manipulation with the `UseAspNetSettings` provider option introduced in version 3.5. (PR  #102)
