### ISSUE TITLE
Consider replacing GetTempFileName with GetTempPath and GetRandomFileName

### ISSUE THREAD

**Issue by jbagga** [aspnet/RoslynCodeDomProvider#9]
Consider removing use of `GetTempFileName` as

> The GetTempFileName method will raise an IOException if it is used to create more than 65535 files without deleting previous temporary files.

The tests CommonCodeDomProviderTests use `GetTempFileName`

See aspnet/Coherence-Signed#510 for more information.

cc @Eilon

**Comment by Eilon** [comment]
@Jinhuafei - this can make test code flaky, which is also a problem. Totally up to your team whether you want to fix.
