### ISSUE TITLE
Go to implementation doesn't work with built source and pdb

### ISSUE THREAD

**Issue by MRatnam** [aspnet/RoslynCodeDomProvider#94]
Go to implementation doesn't work with built source and pdb. Visual Studio says The symbol has no implementations. The modules dialog shows the correct newly generated DLL is referenced and symbols are loaded.

**Comment by StephenMolloy** [comment]
We just published a 3.5-preview1 package with a new symbol package format. Is this still an issue with the current preview package?

**Comment by MRatnam** [comment]
Hi Stephen thanks will give that a go in the next few days.

**Comment by StephenMolloy** [comment]
Closing old, inactive bugs.
