### ISSUE TITLE
Update bundled csc.exe to v3.4.0 to enable C# 8.0

### ISSUE THREAD

**Issue by stevenvolckaert** [aspnet/RoslynCodeDomProvider#95]
We use NuGet package [Microsoft.CodeDom.Providers.DotNetCompilerPlatform v2.0.1](https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/2.0.1) to provide ASP.NET runtime compilation with C# 7.3 support in an ASP.NET Web Site Project (WSP).

This package comes bundled with Roslyn v2.9.0 (`csc.exe` product version = `2.9.0-beta8-63208-01`).

We'd like to enable ASP.NET runtime compilation of C# 8.0 code, so I tried to install Microsoft.Net.Compilers v3.4.0 into our project, but for some reason, `roslyn/csc.exe` in the output directory remains stuck @ v2.9.0.

**Do we need to update the `Microsoft.CodeDom.Providers.DotNetCompilerPlatform`-bundled `csc.exe` to v3.4.0 and release a new version of the package?**

Or: **How can we replace the bundled `csc.exe` in `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` with a newer version?**

**Comment by stevenvolckaert** [comment]
@Jinhuafei Is this repo under active development? Perhaps there is an alternative for using `Microsoft.CodeDom.Providers.DotNetCompilerPlatform`?

Thanks!

**Comment by remcoros** [comment]
We also like to know if this package will be updated and maintained, or should we invest in maintaining our own copy with updated roslyn?

**Comment by MatthijsKrempel** [comment]
I have a PR open with the updated 3.4.0 version of the compilers, need a review on it ;)

**Comment by StephenMolloy** [comment]
Please note that C# 8 is not officially supported on .Net 4.8 and earlier. Many features will probaly work fine, but this is not a recommended configuration to use C# 8 on "desktop" ASP.Net.

In the interest of keeping up with current compilers that support C# 7.3, PR #97 should address this and allow you to experiment with newer versions of C#.

**Comment by stevenvolckaert** [comment]
Thanks @MatthijsKrempel for the PR! 👌❤
Thanks @StephenMolloy for the info!
