### ISSUE TITLE
C# 6 or higher allows property inline initialization, which produces CS1519 compiler error

### ISSUE THREAD

**Issue by vcarlucci** [aspnet/RoslynCodeDomProvider#99]
Following two examples showing a property declaration, part of a class. The class will be assigned as string to the compiler, which should build a class library .dll.

Property declaration working without compiler error:
`public string Name { get; set; }`

Property declaration gives compiler error CS1519:
`public string Name { get; set; } = “Joel“;`

Used NuGet: Microsoft.CodeDom.Providers.DotNetCompilerPlatform 2.0.1

**Comment by StephenMolloy** [comment]
Are you still seeing this issue?

Are the Roslyn CodeDom providers correctly registered in the <system.codedom> section of your config file? If you target .Net 4.5, you should be getting C#6 semantics. Targeting 4.6 or later should get you the "default" language version for the target platform, which is C# 7.3. I don't see any reason you wouldn't be able to use C# 6 features with these packages.
